### ISSUE TITLE
Undefined import: prettyPrintJson

### ISSUE THREAD

**Issue by mreiche** [center-key/pretty-print-json#53]
When I import

```typescript
import { prettyPrintJson } from 'pretty-print-json';
```
then `prettyPrintJson` is `undefined`.
I have no idea why, my IDE IntelliJ has no problems resolving the module and giving type hints.

This is my `tsconfig.json`

```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "target": "es6",
        "module": "esnext",
        "skipLibCheck": true,
        "sourceMap": true,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "lib": [
            "es2019",
            "dom"
        ],
        "moduleResolution": "node",
        "baseUrl": "src"
    },
}
```

I'm using Typescript 3.9.9

**Comment by rakaar** [comment]
I am also facing the same issue @mreiche How did you solve the problem?

**Comment by dpilafian** [comment]
It looks like **IntelliJ** is correctly interpreting the `import` statement because of the `"moduleResolution": "node",` setting.

It's picking up the _**named export**_ from the ES module file:
```js
export { prettyPrintJson };
```
See: https://github.com/center-key/pretty-print-json/blob/main/dist/pretty-print-json.esm.js#L41

I'm taking a wild guess that your build process is somehow using a different configuration and is maybe importing the UMD version or somehow picking up the  _**default export**_:
```js
exports.prettyPrintJson = prettyPrintJson;
```
See: https://github.com/center-key/pretty-print-json/blob/main/dist/pretty-print-json.umd.cjs#L53

The **package.json** file attempts to indicate which version to use:
```json
   "type": "module",
   "main": "dist/pretty-print-json.umd.cjs",
   "module": "dist/pretty-print-json.esm.js",
   "browser": "dist/pretty-print-json.min.js",
```
But maybe that's not quite the right way to do it.

See: https://github.com/center-key/pretty-print-json/blob/main/package.json#L6-L9

Not sure if it's helpful, but here's a working example of importing the _**named export**_:
```js
import { prettyPrintJson } from 'pretty-print-json';
```
See: https://github.com/dnajs/data-dashboard/blob/main/src/web/widgets/network-rest-tool/network-rest-tool.ts#L6

**Comment by christophdebaene** [comment]
I am using webpack and I get the same error when trying to import 

```javascript
import { prettyPrintJson } from 'pretty-print-json';
```

message from webpack:

`export 'prettyPrintJson' (imported as 'prettyPrintJson') was not found in 'pretty-print-json' (module has no exports)`

**Comment by rynangeles** [comment]
I am also having this issue with my angular project. The workaround is to include both the js file and CSS file from the package to the scripts and styles list in the angular.json file. Make sure you add this line to the typings.d.ts file:

    declare var prettyPrintJson as any;

**Comment by dpilafian** [comment]
It looks like **webpack** is picking up the wrong **dist** file.

It's using:
```
dist/pretty-print-json.min.js   <-- has no export (only intended for browsers)
```
instead of:
```
dist/pretty-print-json.esm.js
```

I created a default Angular project and was able to easily replicate the problem.  After installing and importing `pretty-print-json`, the `npm run build` command generates the **"module has no exports"** error.

Then I went into the the **node_modules/pretty-print-json/package.json** file and deleted the line:
```json
  "browser": "dist/pretty-print-json.min.js",
```

Now the `npm run build` command works without errors, and the `prettyPrintJson` variable is defined as expected.  This identifies the problem, but it's not obvious how to correctly fix it.

Anyone know the correct way to configure a library, like `pretty-print-json`, to tell **webpack** to use the `module` version?

**Comment by dpilafian** [comment]
The `exports` setting in **package.json** looks promising:
https://webpack.js.org/guides/package-exports/#abbreviation

May also get some help on SO:
https://stackoverflow.com/q/68173241

**Comment by dpilafian** [comment]
**node** and **webpack** did not create the js library management shitshow, but they did turn it into a raging dumpster fire.

Anyway, this `exports` setting should configure the imports correctly*:
```json
   "exports": {
      ".": {
         "import": "./dist/pretty-print-json.esm.js",
         "require": "./dist/pretty-print-json.umd.cjs"
      },
      "./": "./dist/"
   },
```
*may require **webpack** v5.0.
